### ISSUE TITLE
Cant search multiples pages while working with Google()

### ISSUE THREAD

**Issue by Durga260996** [tasos-py/Search-Engines-Scraper#12]
```
from search_engines import Google, Bing, Yahoo, Ask, Dogpile, Duckduckgo, Aol, Mojeek, Startpage
google = {}
action_words = ['affimative action']

def search_word(words):
      for word in words:
            engine = Google()
            results = engine.search(word, pages = 10)
            links = results.links()
            num = 1
            for link in links:
                google[num] = link
                num = num+1

search_word(action_words)
```

The output shows only the first 10 links. It would be really helpful if you can let me know what I am doing wrong. I would like to extract all the links in the first 10 pages. 

I checked with bing and yahoo which are working fine and I am able to get all the links in the first 10 pages.   

Duckduckgo and Startpage are not working

**Comment by tasos-py** [comment]
Thanks for bringing this to my attention. It seems we have to change the selectors for those three search engines.

**Comment by tasos-py** [comment]
Fixed the next page selector for Google, now it should return more than one pages. I think Duckduckgo and Startpage made much more drastic changes to their HTML structure and it will take some time to update the code. It's probably doable (unless Js is absolutely necessary for HTML to  render) and I'll take care of it when I have a couple of hours to spare.

**Comment by Durga260996** [comment]
Thank you! I am looking forward to the update.
