### ISSUE TITLE
ERROR A Connection error occurred. 

### ISSUE THREAD

**Issue by bbkali** [tasos-py/Search-Engines-Scraper#14]
no result

response:
Searching Yahoo                                                                                     
ERROR A Connection error occurred.                                                                  
                                                                                                    
Yahoo results

**Comment by tasos-py** [comment]
This is probably related to your network config, I'm not sure I can do much about it. Are you using any proxies? Does this happen often with Yahoo? Does it happen with other engines?

**Comment by bbkali** [comment]
After configuring proxy in config, it can be used normally. Thank you. Set HTTP in the terminal export_ Proxy after running is burst out of this error, this program is very good! But I found out if we use advanced search syntax, whether some search engines do not support or do not have search results, such as search inurl:MP3 inurl : login.asp

**Comment by tasos-py** [comment]
There is a [`Engine.set_search_operator()`](https://github.com/tasos-py/Search-Engines-Scraper/blob/master/search_engines/engine.py#L127) method that accepts some basic operators (url, title, text, host), but it's not that well developed to be honest. It basically filters search results based on the operators(s) set - if the query is in the space of the operator it keeps the item, otherwise it ignores it. It's best to use the engine's operators, when available.

**Comment by bbkali** [comment]
Thank you. When I look at the code, I can see that it contains the logic of filtering, whether it can add the logic of combining or of multiple keywords, and whether it can add the query function of Baidu, yandex and other search engines

**Comment by tasos-py** [comment]
Yes, as you noticed the code is simple and modular, and it should be easy to add new functionality or modify the existing one. I think Baidu and Yandex require a client that runs Js, so you would have to use browser automation. The easiest way to do that is to create a new `HttpClient` class that uses Selenium or similar libs.

**Comment by bbkali** [comment]
Using selenium and JS, I have tested Baidu and yandex. It is also easy to detect the need to enter a verification code. I found yandex can pass the API. Maybe we can take advantage of this

**Comment by tasos-py** [comment]
That's awesome! I don't plan to add more engines, we already have ten! Besides, browser automation would add complexity, which I'm not sure is needed. However, this repo is under MIT license, so feel free to clone and experinment or propose a contribution, if you're happy with the results.
