### ISSUE TITLE
Limit search results. 

### ISSUE THREAD

**Issue by chsaiujwal** [tasos-py/Search-Engines-Scraper#15]
Is there anyway I can limit number of output results? Like I need only 10 Google search results...
I used below code and it gave too many results...
`from search_engines import Google

engine = Google()
results = engine.search("my query")
links = results.links()`

Thanks in advance.

**Comment by chsaiujwal** [comment]
Nevermind, god it.

**Comment by stuartathompson** [comment]
@chsaiujwal can you post your answer for others?
