### ISSUE TITLE
Startpage search not working?

### ISSUE THREAD

**Issue by matalab** [tasos-py/Search-Engines-Scraper#16]
Hello, while other engines do provide results, Startpage gives no results for even most simple search terms. Can you please check it, does it work or maybe something changed with Startpage in meantime, so it does not work anymore?

**Comment by tasos-py** [comment]
I know, they changed their search form and we have to update the code. I'll fix it when I have some spare time, probably in a week or two.

**Comment by tasos-py** [comment]
Fixed it.

**Comment by matalab** [comment]
Great! Thank you!
