### ISSUE TITLE
want to ask about proxy

### ISSUE THREAD

**Issue by bshelly-web** [tasos-py/Search-Engines-Scraper#23]
Is there proxy support in this scrapper? so search engine do not block us

**Comment by tasos-py** [comment]
Sure, it supports HTTP/S and SOCKS proxies. If you're using the CLI script, use the `-proxy` parameter, eg `-proxy http://127.0.0.1:8888`. If you're using it as a library, it's the first parameter of the constructor, eg `engine = Google('http://127.0.0.1:8888')`
