### ISSUE TITLE
Torch search engine outdated

### ISSUE THREAD

**Issue by wapaja5132** [tasos-py/Search-Engines-Scraper#25]
Hi
I tried to run a test with torch but it seems that the torch url is no longer available, the new one is http://torchdeedp3i2jigzjdmfpn5ttjhthh5wbmda2rr3jvqjg5p77c54dqd.onion

Do you plan to upgrade the engine?

Thanks!

**Comment by tasos-py** [comment]
Thanks for letting me know. I updated `Torch`, it should be fine now.

**Comment by wapaja5132** [comment]
it works fine!!

Many thanks
