### ISSUE TITLE
How to stop repeating results?

### ISSUE THREAD

**Issue by Light-Lens** [tasos-py/Search-Engines-Scraper#27]
As you said that if i use flag "-i" then, it will not repeat results, but it's doing that. Can you please guide me how to use this feature?
Thank you!

**Comment by tasos-py** [comment]
You're right, the "-i" flag has no effect on the CLI script. Note that if you use `.ignore_duplicate_urls=True`, it will remove duplicates from `MultipleSearchEngines.results`, but the console output is based on each `SearchEngine.results` separately. I'll fix it.

**Comment by tasos-py** [comment]
Done.

**Comment by Light-Lens** [comment]
Thanks,  I was actually building a search engine, [Studybyte](https://github.com/Light-Lens/Studybyte), So i needed a simple crawler which can crawl results from Google, Bing and DuckDuckGo. Also no worries, i created a custom script which will remove duplicates. This tool actually saved hours of time. THANK YOU!
