### ISSUE TITLE
Feature request for YouTube

### ISSUE THREAD

**Issue by Light-Lens** [tasos-py/Search-Engines-Scraper#29]
Hey, please consider adding YouTube results too, if possible.
Thanks :)

**Comment by tasos-py** [comment]
Sorry, I don't plan to add YouTube in Search-Engines-Scraper ...because it's not a search engine! But I'm sure you'll find what you're looking for somewhe in github, https://github.com/search?q=youtube+scraper

**Comment by Light-Lens** [comment]
> Sorry, I don't plan to add YouTube in Search-Engines-Scraper ...because it's not a search engine! But I'm sure you'll find what you're looking for somewhe in github, https://github.com/search?q=youtube+scraper

Thanks :)
