### ISSUE TITLE
Bing empty results

### ISSUE THREAD

**Issue by soxoj** [tasos-py/Search-Engines-Scraper#34]
I am getting empty results for Bing search, is its scraping engine actual?

**Comment by tasos-py** [comment]
I don't have any issues at all with Bing. Perhaps your query doesn't produce results, do you get any results with any queries at all?

**Comment by soxoj** [comment]
It happens with any request, empty html without results (see pic below, second is the normal desktop answer). I checked with a foreign proxy, and results appeared. Looks like a geoban as for Qwant (#35).
Thanks for checking, I think nothing can be solved with this at the tool level.

<img width="733" alt="bing_search_engine_scraper" src="https://user-images.githubusercontent.com/31013580/145200507-039255ed-9b05-44aa-954b-84246ed16175.png">
<img width="697" alt="bing_desktop" src="https://user-images.githubusercontent.com/31013580/145200513-1b85b603-a14e-4fc1-ac85-123e6d07bb24.png">
