### ISSUE TITLE
Yahoo title parsing improving

### ISSUE THREAD

**Issue by soxoj** [tasos-py/Search-Engines-Scraper#38]
I noticed that title of Yahoo is extracted incorrectly:
```
URL: https://gist.github.com/soxoj/9d65c2f4d3bec5dd25949197ea73cf3a
Title: gist.github.com › soxoj › 9d65c2f4d3bec5dd25949197eamaigret.ipynb · GitHub
``` 
Title should be `maigret.ipynb · GitHub`

I did some fixes form my other project [here](https://github.com/soxoj/marple/commit/60df5b7b15cac572466b018155af59ffcfa07e62#diff-4baf5bdbb8bd7ace489872c9b2f1562207c72d2a181091210b4f77f548a26773R236)

**Comment by tasos-py** [comment]
Nice catch! I fixed it with bs4's `.decompose()`, but I'll keep this open in case there is more work to be done
