### ISSUE TITLE
Can I use this project for image search?

### ISSUE THREAD

**Issue by rider8581** [tasos-py/Search-Engines-Scraper#39]
Hi there,
Thank you for your contribution.
I have a question while using this script.
Can I use this script for image search?
For example, instead of query string, can I put the byte string of data image to perform image search?
Kindly let me know what you think.
Thank you so much.

**Comment by tasos-py** [comment]
No, this repo only provides web results. If you want to search for images or if you're looking for something like google's "/search?tbs=sbi:" or bing's "/images/search?q=imgurl:" utilities, maybe you could subclass a search engine(s), modify it accordingly, and add it to `engines`, as described in https://github.com/tasos-py/Search-Engines-Scraper#features.

**Comment by rider8581** [comment]
OK, noted, thanks for comment
