### ISSUE TITLE
Locale Handling

### ISSUE THREAD

**Issue by davidlenz** [tasos-py/Search-Engines-Scraper#4]
Great Project, thanks a ton!
Wonder how to set the locale, e.g. en-US, given a search engine object?

What i currently do is to set
`self.session.headers.update({"Accept-Language": "en-US"})`

in the http_client, e.g. [right here](https://github.com/tasos-py/Search-Engines-Scraper/blob/master/search_engines/http_client.py#L14).

Is there any other or maybe preferred way?

**Comment by tasos-py** [comment]
No, there isn't any other way to set headers. The http client is a private attribute and is only accesible via a `.set_user_agent()` method, which obviously doesn't modify any headers other than the User-Agent. I didn't think that it may be needed to set other headers, but it seems I was wrong. I replaced `.set_user_agent()` with a `.set_headers()` method so now you can use this to set headers.  

Thanks for bringing this to my attention.

**Comment by davidlenz** [comment]
Amazing! Thanks for the very quick response.
