### ISSUE TITLE
How to stop the search

### ISSUE THREAD

**Issue by stuartathompson** [tasos-py/Search-Engines-Scraper#40]
Sorry for posting a rudimentary question but there is no real instruction or documentation. 

After putting in the example it keeps searching Google non-stop. How am I supposed to interrupt this or set other options?

```
engine = Google()
results = engine.search("my query")
links = results.links()
```

**Comment by tasos-py** [comment]
It's not mentioned in readme, but there are options to limit or interrupt `.search()`. To limit the number of results, simply set the [`.search(pages=)`](https://github.com/tasos-py/Search-Engines-Scraper/blob/master/search_engines/engine.py#L148) argument to a lower number. For example, the code below will request only the first two pages, 
~~~
    results = engine.search("my query", 2)
~~~

If you want to stop a running `.search()`, you could use a keyboard interrupt signal (CTRL+C). KeyboardInterrupt exceptions are caught internally in `.search()`, and they cause it to stop making requests and return the results.  

Also, in [other-versions](https://github.com/tasos-py/Search-Engines-Scraper#other-versions) you'll find an async version of this project, that should allow you to tun it in the background.

**Comment by tasos-py** [comment]
No, there is no documentation, besides what's in README. If you have the time to write something, you're welcome to contribute. A good place to start is the parent class, "/search_engines/engine.py". Its public methods have short docstrings
