### ISSUE TITLE
Feature request Brave search engine 

### ISSUE THREAD

**Issue by chirag127** [tasos-py/Search-Engines-Scraper#49]
Thanks for your work, Please consider adding Brave search support if possible

**Comment by tasos-py** [comment]
It sounds interesting. I'm a little busy now, but I'll check it out when I have some spare time

**Comment by tasos-py** [comment]
I added Brave

**Comment by chirag127** [comment]
no captcha or any thing?

**Comment by tasos-py** [comment]
Do they have a captcha? I haven't encountered a captcha in my tests so far.
