### ISSUE TITLE
Feature request; toggle console output for searches

### ISSUE THREAD

**Issue by deKeijzer** [tasos-py/Search-Engines-Scraper#58]
Hi there! 

In engine.py there are three uses of out.console(...) within search(), can this output be made into a toggle? It should be relatively easy and it would avoid console spam when using the search engine in e.g. a tqdm loop. 

Bests

**Comment by tasos-py** [comment]
Sorry for the late reply, I somehow missed this issue. What you propose makes sense, and I plan to implement it as soon as I have the time. Thanks

**Comment by zadamg** [comment]
Came here to ask for the same <3
