### ISSUE TITLE
Bing can't get a result

### ISSUE THREAD

**Issue by lydia07** [tasos-py/Search-Engines-Scraper#6]
The goole engine can be used successfully, while Bing can't.
I wrote test code like this:
```
engine = Bing()
results = engine.search("apple",pages=1)
links = results.links()
print(links)
```
However, the result is an empty list. I tested Google as well, it was fine. So I am really confused about this problem.
Thanks for your reply!

**Comment by lydia07** [comment]
It seems like I can only search a single word in Bing. How can I fix this?

**Comment by tasos-py** [comment]
It seems Bing doesn't like our user-agent anymore :( I think it's more ethical to let them know that we're a bot, but sometimes user-agent spoofing can't be avoided. The user-agent and other headers can be changed with `.set_headers()`, eg:  

```
engine = Bing()
engine.set_headers({'User-Agent':'My User-Agent string'})
...
```

Also, I've updated the repo, so `Bing` uses a fake user-agent (Firefox) from now on.  

Thanks for noticing this issue.

**Comment by lydia07** [comment]
Thanks! That is really helpful ：）
