### ISSUE TITLE
How to use proxy server?

### ISSUE THREAD

**Issue by matalab** [tasos-py/Search-Engines-Scraper#60]
Hello, can you please explain how to set and use a proxy?

**Comment by tasos-py** [comment]
Sure, it's easy. If you use the CLI script you can use the `-proxy` argument, 
```
$ python search_engines_cli.py -e google -q "query" -proxy "http://127.0.0.1:8080"
```
and if you import it use the 1st argument in the constructor, 
```
proxy = "http://127.0.0.1:8080"
engine = Google(proxy)
```

**Comment by matalab** [comment]
Thank you, both for the answer and for your great package!
Do you have any recommendation on free and paid proxy lists/APIs?
