### ISSUE TITLE
Collect more than 10 results + get meta description

### ISSUE THREAD

**Issue by IKDH** [tasos-py/Search-Engines-Scraper#68]
Hello,

I can't manage to get more than 10 results for a keyword. Is there a way to set up this parameter ?

Also, is it possible to get the meta description for each URL. The one that Google display, not the one set up by the owner of the website.

Thank you!

**Comment by tasos-py** [comment]
Thanks for informing me, I'll see to it

**Comment by tasos-py** [comment]
About your first question, yes you can get more results by increasing the number of pages. if you're using the CLI script you can set pages with the `-p=` argument, and if you're using it as a lib you can set the [`pages=`](https://github.com/tasos-py/Search-Engines-Scraper/blob/master/search_engines/engine.py#L152) argument.

About the second thing, I'm not sure what you mean. File outputs contain most of what search engines display, including title and text, For example, a google search for "test" produces results like, 
```
            {
                "host": "speedtest.net",
                "link": "https://www.speedtest.net/",
                "title": "Speedtest by Ookla - The Global Broadband Speed Test",
                "text": "Download the Speedtest app for more metrics, video testing, mobile coverage maps, and more. Get it on Google Play."
            },
```
Isn't that sufficient enough?
