### ISSUE TITLE
How to search more pages and links

### ISSUE THREAD

**Issue by qiankunlee** [tasos-py/Search-Engines-Scraper#70]
Hello, thanks for your work very much. I have a question now, how to search more results like links, I have changed the parameter of 'SEARCH_ENGINE_RESULTS_PAGES', but it doesn't work!

**Comment by qiankunlee** [comment]
The SEARCH_ENGINE_RESULTS_PAGES is in config.py

**Comment by tasos-py** [comment]
Hi, it's very easy to set the max number of pages. For the CLI script you can use the `-p` argument, and for the lib the `.search(pages=)` argument. However, the actual number of pages can be smaller, depending on the query and search engine. For example Google doesn't go further than the 2-3rd page sometimes
