### ISSUE TITLE
Error an ssl error occurred. 

### ISSUE THREAD

**Issue by mart-exsell** [tasos-py/Search-Engines-Scraper#9]
Hi, i like the code you wrote. unfortunately i am now experiencing the following error when scraping bing:
ERROR An SSL error occurred. 

Are there any search engines that don't ban their users for scraping? 

Kind regards,
Mart

**Comment by tasos-py** [comment]
That's strange. Are you getting this error with all search engines or only with Bing? Are you using any proxies/VPNs? If you're using an intercepting proxy, you can disable SSL verification with   
```
bing = Bing()
bing._http_client .session.verify = False
```  
It may help us identify the problem if we have the full exception message. Can you go to `search_engines/http_client.py`, line 21 and remove the `try-except` block? `HttpClient.get()` should look like this:  
```  
    def get(self, page):
        '''Submits a HTTP GET request.'''
        page = self._quote(page)
        req = self.session.get(page, timeout=self.timeout)
        self.session.headers['Referer'] = page
        return self.response(http=req.status_code, html=req.text)
```

As far as I know, only Google bans scraping, but most other search engines have rate-limiting mechanisms. You could avoid triggering those mechanisms by using rotating proxies or by increasing the delay between requests. You can do that with  
```
bing = Bing()
bing._delay = (4, 6)
```
